'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, CheckCircle2, ChevronRight, CircleHelp, Database, Download, FileText, Home, Leaf, Menu, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Upload, Users, X } from 'lucide-react'
import { api } from '@/lib/api'
import { CowBot } from '@/components/cow-bot'
import { Chart, type ChartSpec } from '@/components/chart'
import { Prediccion } from '@/components/prediccion'
import { assessRisk, getSummary } from '@/lib/risk-engine'
import type { Cow, CowStatus, RiskLevel, View } from '@/lib/types'

const nav: { id: View; label: string; icon: typeof Home }[] = [
  { id: 'inicio', label: 'Inicio', icon: Home }, { id: 'vacas', label: 'Vacas', icon: Users }, { id: 'alertas', label: 'Alertas', icon: Bell }, { id: 'analisis', label: 'Análisis', icon: BarChart3 }, { id: 'datos', label: 'Datos', icon: Database }, { id: 'modelo', label: 'Modelo', icon: Sparkles }, { id: 'configuracion', label: 'Configuración', icon: Settings },
]

function Badge({ level }: { level: RiskLevel }) { return <span className={`badge badge-${level.toLowerCase()}`}><span className="badge-dot" />{level}</span> }
function Logo() { return <div className="brand"><div className="brand-mark"><Leaf size={19} /></div><div><strong>Campo<span>Claro</span></strong><small>Alerta reproductiva bovina</small></div></div> }
function Button({ children, onClick, variant = 'primary', type = 'button' }: { children: React.ReactNode; onClick?: () => void; variant?: 'primary' | 'outline' | 'ghost'; type?: 'button' | 'submit' }) { return <button type={type} onClick={onClick} className={`btn btn-${variant}`}>{children}</button> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }
function PageTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="page-title"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }

function Landing({ enter }: { enter: () => void }) { return <main className="landing"><section className="hero-photo"><div className="hero-overlay" /><header className="landing-header"><Logo /><nav><a href="#como-funciona">Cómo funciona</a><a href="#alcance">Alcance del MVP</a><Button onClick={enter} variant="outline">Abrir demo <ArrowRight size={16} /></Button></nav></header><div className="hero-inner"><div className="pill"><span /> Sistema de apoyo a la decisión</div><h1>Inteligencia artificial<br /><em>con los pies en el campo.</em></h1><p className="hero-lead">Un modelo entrenado clasifica el estado reproductivo de cada vaca y te explica en qué se apoya. Tú decides.</p><div className="hero-actions"><Button onClick={enter}>Explorar el dashboard <ArrowRight size={17} /></Button><a href="#como-funciona" className="text-link">Conocer el enfoque <ChevronRight size={15} /></a></div><p className="microcopy"><ShieldCheck size={14} /> Línea base transparente · No reemplaza criterio veterinario</p></div><div className="hero-stats"><div><strong>6</strong><span>Vacas monitoreadas</span></div><div><strong className="amber-text">2</strong><span>En riesgo alto</span></div><div><strong>11.8 <small>meses</small></strong><span>Intervalo promedio</span></div><div><strong>14 <small>meses</small></strong><span>Umbral de alerta</span></div></div></section><div className="trust-strip"><span>Diseñado para decisiones cotidianas</span><div><span><CheckCircle2 size={15} /> Datos legibles</span><span><CheckCircle2 size={15} /> Reglas explicables</span><span><CheckCircle2 size={15} /> Sin cajas negras</span></div></div><section id="como-funciona" className="landing-section"><div><p className="eyebrow">El enfoque</p><h2>Menos ruido.<br /><span>Más contexto.</span></h2></div><div className="feature-grid"><div><div className="feature-icon"><Activity size={19} /></div><h3>Ordena la atención</h3><p>Identifica rápidamente qué animales merecen una revisión prioritaria según sus registros actuales.</p></div><div><div className="feature-icon"><SlidersHorizontal size={19} /></div><h3>Explica cada señal</h3><p>Los factores visibles detrás de cada nivel evitan interpretar un resultado sin contexto.</p></div><div><div className="feature-icon"><FileText size={19} /></div><h3>Parte de tus datos</h3><p>Una base preparada para crecer desde CSV hacia una integración productiva.</p></div></div></section></main> }

function Sidebar({ view, setView, mobile, close }: { view: View; setView: (v: View) => void; mobile: boolean; close: () => void }) { return <aside className={`sidebar ${mobile ? 'mobile-open' : ''}`}><div className="sidebar-head"><Logo />{mobile && <button className="icon-btn" onClick={close} aria-label="Cerrar menú"><X size={19} /></button>}</div><div className="demo-note"><span className="pulse" /><div><strong>Modo demostración</strong><small>Datos sintéticos locales</small></div></div><nav className="side-nav">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); close() }}><Icon size={18} /><span>{label}</span>{id === 'alertas' && <b>2</b>}</button>)}</nav><div className="sidebar-bottom"><div className="help-box"><CircleHelp size={17} /><div><strong>¿Necesitas ayuda?</strong><span>Conoce el significado de los indicadores.</span></div></div><div className="user-row"><div className="avatar">OP</div><div><strong>Operador demo</strong><span>Establecimiento Norte</span></div><ChevronRight size={16} /></div></div></aside> }

function Kpi({ label, value, detail, tone = '' }: { label: string; value: string; detail: string; tone?: string }) { return <div className="kpi"><div className="kpi-label">{label}</div><strong className={tone}>{value}</strong><span>{detail}</span></div> }
function RiskChart({ cows }: { cows: Cow[] }) { const counts = { Bajo: 0, Medio: 0, Alto: 0 } as Record<RiskLevel, number>; cows.forEach(c => counts[assessRisk(c).level]++); return <div className="risk-chart"><div className="donut" style={{ background: `conic-gradient(var(--risk-high) 0 ${counts.Alto / cows.length * 100}%, var(--risk-medium) ${counts.Alto / cows.length * 100}% ${(counts.Alto + counts.Medio) / cows.length * 100}%, var(--risk-low) ${(counts.Alto + counts.Medio) / cows.length * 100}% 100%)` }}><div><strong>{cows.length}</strong><span>vacas</span></div></div><div className="legend"><div><i className="dot high" /><span>Alto</span><strong>{counts.Alto}</strong></div><div><i className="dot medium" /><span>Medio</span><strong>{counts.Medio}</strong></div><div><i className="dot low" /><span>Bajo</span><strong>{counts.Bajo}</strong></div></div></div> }

function Dashboard({ cows, addCow, reload, view, setView, charts, clearCharts }: { cows: Cow[]; addCow: () => void; reload: () => void; view: View; setView: (v: View) => void; charts: ChartSpec[]; clearCharts: () => void }) { const [selected, setSelected] = useState<Cow | null>(null); const summary = getSummary(cows); const [search, setSearch] = useState(''); const [filter, setFilter] = useState<'Todos' | RiskLevel>('Todos'); const filtered = cows.filter(c => c.earTag.toLowerCase().includes(search.toLowerCase()) && (filter === 'Todos' || assessRisk(c).level === filter)); const high = [...cows].sort((a, b) => assessRisk(b).score - assessRisk(a).score).slice(0, 4)
  if (selected) return <Detail cow={selected} back={() => setSelected(null)} />
  const bloqueGraficas = charts.length ? <div className="viz-section"><div className="viz-section-head"><div><p className="eyebrow">Generado por Vaky</p><h2>{charts.length === 1 ? 'Gráfica de Vaky' : `${charts.length} gráficas de Vaky`}</h2></div><button className="more-btn" onClick={clearCharts}><X size={14} /> Limpiar</button></div><div className="viz-grid">{charts.map((c, i) => <Chart key={`${c.titulo}-${i}`} spec={c} />)}</div></div> : null
  if (view === 'inicio') return <><PageTitle eyebrow="Resumen del establecimiento" title="Buenos días, operador" description="Esta es la lectura actual del rodeo y sus principales señales." action={<Button onClick={() => setView('vacas')}><Plus size={17} /> Registrar vaca</Button>} /><div className="demo-banner"><div className="banner-icon"><Sparkles size={18} /></div><div><strong>Modo demostración activo</strong><span>Estás explorando datos sintéticos. La clasificación usa una regla base transparente, no un modelo ML entrenado.</span></div><button onClick={() => setView('modelo')}>Ver cómo funciona <ArrowRight size={15} /></button></div><div className="kpi-grid"><Kpi label="Vacas monitoreadas" value={String(summary.total)} detail="100% de la base cargada" /><Kpi label="Riesgo alto" value={String(summary.high)} detail="Requieren atención prioritaria" tone="red-text" /><Kpi label="Intervalo promedio" value={`${summary.averageInterval.toFixed(1)} m`} detail="Objetivo de referencia: 14 m" /><Kpi label="Producción promedio" value={`${summary.averageMilk.toFixed(1)} L`} detail="Litros por vaca y día" /></div><div className="dashboard-grid"><Card><div className="card-head"><div><h2>Distribución de riesgo</h2><p>Según el intervalo entre partos actual</p></div><button className="more-btn" onClick={() => setView('analisis')}>Ver análisis <ArrowRight size={15} /></button></div><RiskChart cows={cows} /><div className="chart-note"><span>Umbral de referencia: 14 meses</span><span className="risk-line" /></div></Card><Card><div className="card-head"><div><h2>Intervalo por vaca</h2><p>Meses desde el último parto</p></div></div><div className="bar-chart">{cows.map(c => <div className="bar-item" key={c.id}><div className="bar-wrap"><div className={`bar ${assessRisk(c).level.toLowerCase()}`} style={{ height: `${Math.min(100, c.intervalMonths / 18 * 100)}%` }}><span>{c.intervalMonths.toFixed(1)}</span></div><div className="threshold" /></div><small>{c.earTag.replace('BOV-', '#')}</small></div>)}</div><div className="axis"><span>0 m</span><span>14 m</span><span>18 m</span></div></Card></div><Card className="priority-card"><div className="card-head"><div><h2>Atención priorizada</h2><p>Vacas ordenadas por señales de riesgo</p></div><button className="more-btn" onClick={() => setView('alertas')}>Ver todas las alertas <ArrowRight size={15} /></button></div><CowTable cows={high} onSelect={setSelected} compact /></Card>{bloqueGraficas}</>
  if (view === 'vacas') return <><PageTitle eyebrow="Registro del rodeo" title="Vacas" description={`${cows.length} animales en la base de datos demo.`} action={<Button onClick={() => addCow()}><Plus size={17} /> Registrar vaca</Button>} /><div className="toolbar"><div className="search"><Search size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por caravana..." /></div><select value={filter} onChange={e => setFilter(e.target.value as typeof filter)}><option>Todos</option><option>Alto</option><option>Medio</option><option>Bajo</option></select></div><Card className="table-card"><CowTable cows={filtered} onSelect={setSelected} /></Card></>
  if (view === 'alertas') return <><PageTitle eyebrow="Seguimiento recomendado" title="Alertas" description="Señales que ayudan a ordenar la próxima revisión." /><div className="alert-list">{high.map(c => { const a = assessRisk(c); return <Card key={c.id} className="alert-card"><div className="alert-top"><div className={`alert-icon ${a.level.toLowerCase()}`}><AlertTriangle size={19} /></div><div><div className="alert-name"><strong>{c.earTag}</strong><Badge level={a.level} /></div><span>{c.breed} · Paridad {c.parity} · Estado: {c.status}</span></div><button className="more-btn" onClick={() => setSelected(c)}>Ver ficha <ChevronRight size={15} /></button></div><div className="reason-list">{a.reasons.map(r => <span key={r}><CheckCircle2 size={14} />{r}</span>)}</div><div className="alert-action"><span>Apoyo sugerido: <strong>{a.action}</strong></span><span className="alert-data">Intervalo <b>{c.intervalMonths.toFixed(1)} m</b></span></div></Card> })}</div></>
  if (view === 'analisis') return <Analysis cows={cows} />
  if (view === 'datos') return <DataView cows={cows} reload={reload} />
  if (view === 'modelo') return <ModelView apiBase={api.baseUrl} />
  return <SettingsView />
}

function CowTable({ cows, onSelect, compact = false }: { cows: Cow[]; onSelect: (c: Cow) => void; compact?: boolean }) { return <div className="table-scroll"><table><thead><tr><th>Vaca</th><th>Riesgo</th><th>Intervalo</th><th>Condición corporal</th><th>Producción</th><th /></tr></thead><tbody>{cows.map(c => { const a = assessRisk(c); return <tr key={c.id} onClick={() => onSelect(c)}><td><div className="cow-name"><div className="cow-avatar">{c.earTag.slice(-3)}</div><div><strong>{c.earTag}</strong><span>{c.breed} · {c.status}</span></div></div></td><td><Badge level={a.level} /></td><td><strong>{c.intervalMonths.toFixed(1)} m</strong><span className="cell-muted">{c.intervalMonths >= 14 ? 'Sobre umbral' : 'En rango'}</span></td><td>{c.bodyCondition.toFixed(1)} / 5</td><td>{c.milkLiters.toFixed(1)} L/día</td><td><ChevronRight size={17} className="row-arrow" /></td></tr> })}</tbody></table>{!cows.length && <div className="empty">No se encontraron vacas con esos filtros.</div>}</div> }

function Detail({ cow, back }: { cow: Cow; back: () => void }) { const a = assessRisk(cow); return <><button className="back-link" onClick={back}><ArrowRight size={15} /> Volver a vacas</button><PageTitle eyebrow="Ficha individual" title={cow.earTag} description={`${cow.breed} · Nacida el ${cow.birthDate} · ${cow.status}`} action={<Badge level={a.level} />} /><div className="detail-grid"><Card><div className="card-head"><div><h2>Evaluación de riesgo</h2><p>Línea base heurística</p></div><div className={`score ${a.level.toLowerCase()}`}>{a.score}<small>/100</small></div></div><div className="risk-summary"><Badge level={a.level} /><strong>{a.action}</strong></div><div className="reason-list detail-reasons">{a.reasons.map(r => <span key={r}><CheckCircle2 size={14} />{r}</span>)}</div><div className="not-available"><Sparkles size={16} /><div><strong>Predicción ML no disponible</strong><span>Esta demo usa una regla de referencia para ilustrar el flujo. No representa un modelo entrenado.</span></div></div></Card><Card><div className="card-head"><div><h2>Datos productivos</h2><p>Últimos valores registrados</p></div></div><div className="metric-list"><div><span>Intervalo entre partos</span><strong>{cow.intervalMonths.toFixed(1)} meses</strong></div><div><span>Condición corporal</span><strong>{cow.bodyCondition.toFixed(1)} / 5</strong></div><div><span>Producción diaria</span><strong>{cow.milkLiters.toFixed(1)} litros</strong></div><div><span>Eventos sanitarios</span><strong>{cow.healthEvents}</strong></div></div></Card><Card className="wide-card"><div className="card-head"><div><h2>Historial reproductivo</h2><p>Registro disponible para esta vaca</p></div></div><div className="timeline"><div><span>Último parto</span><strong>{cow.lastCalving}</strong></div><div><span>Último servicio</span><strong>{cow.lastService}</strong></div><div><span>Paridad</span><strong>{cow.parity}</strong></div></div><p className="notes">{cow.notes || 'Sin observaciones adicionales registradas.'}</p></Card></div></> }

function Analysis({ cows }: { cows: Cow[] }) { const avg = getSummary(cows).averageInterval; return <><PageTitle eyebrow="Lectura de la base" title="Análisis" description="Una vista para entender el comportamiento de los intervalos, no para reemplazar una evaluación profesional." /><div className="analysis-hero"><div><div className="pill small-pill"><Activity size={14} /> Interpretación orientativa</div><h2>El intervalo entre partos<br /><em>es la señal central.</em></h2><p>La línea base marca como riesgo alto a las vacas con 14 meses o más desde su último parto. El objetivo es hacer visible dónde mirar primero.</p></div><div className="big-stat"><strong>{avg.toFixed(1)}</strong><span>meses promedio<br />en el rodeo</span></div></div><div className="analysis-grid"><Card><h2>¿Qué significa el umbral?</h2><p>Los 14 meses funcionan aquí como una referencia operativa para iniciar una conversación sobre el caso: revisar eventos, condición corporal, servicios y registros faltantes.</p><div className="threshold-box"><div><span>En rango</span><strong>&lt; 12 meses</strong></div><div><span>Seguimiento</span><strong>12 – 14 meses</strong></div><div><span>Prioridad</span><strong>≥ 14 meses</strong></div></div></Card><Card><h2>Variables que acompañan</h2><div className="variable-list"><span><b>Condición corporal</b><small>Contextualiza el estado actual.</small></span><span><b>Eventos sanitarios</b><small>Ayuda a explicar desvíos.</small></span><span><b>Producción</b><small>Permite leer el contexto productivo.</small></span></div></Card></div></> }
function DataView({ cows, reload }: { cows: Cow[]; reload: () => void }) { const download = () => { window.open(api.exportUrl(), '_blank') }; const upload = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { const r = await api.importCsv(file); alert(`Importación lista: ${r.created} creadas, ${r.updated} actualizadas, ${r.skipped} omitidas.`); reload() } catch (err) { alert(`No se pudo importar: ${(err as Error).message}`) } finally { e.target.value = '' } }; return <><PageTitle eyebrow="Base de información" title="Datos" description="Revisa las variables disponibles y gestiona el archivo de trabajo de la demo." action={<Button onClick={download}><Download size={17} /> Exportar CSV</Button>} /><div className="data-cards"><Card><Database size={20} /><strong>{cows.length}</strong><span>registros cargados</span></Card><Card><FileText size={20} /><strong>8</strong><span>variables principales</span></Card><Card><CheckCircle2 size={20} /><strong>100%</strong><span>de la base validada</span></Card></div><Card className="import-card"><div className="import-icon"><Upload size={21} /></div><div><h2>Importar registros</h2><p>Sube un archivo CSV con los encabezados de la exportación. Se valida y persiste en el backend (SQLite).</p></div><label className="btn btn-outline" style={{ cursor: 'pointer' }}><Upload size={16} /> Seleccionar CSV<input type="file" accept=".csv,text/csv" onChange={upload} hidden /></label></Card><Card className="table-card"><div className="card-head"><div><h2>Vista previa de la base</h2><p>Datos demo sintéticos</p></div><span className="source-tag">SQLite · API</span></div><CowTable cows={cows.slice(0, 4)} onSelect={() => {}} /></Card></> }
function ModelView({ apiBase }: { apiBase: string }) { return <><PageTitle eyebrow="Transparencia del sistema" title="Modelo" description="Clasifica una vaca con el modelo entrenado y conoce en qué se apoya el resultado." /><div className="model-status"><div className="model-orb"><Sparkles size={24} /></div><div><span className="eyebrow">Estado actual</span><h2>Modelo entrenado y en servicio</h2><p>Gradient Boosting sobre 2.000 vacas, F1 macro de 0.871 en datos que no vio. Predice la clasificación reproductiva: Mala, Regular, Buena o Excelente.</p></div><span className="status-chip">Activo</span></div><Prediccion apiBase={apiBase} /><div className="model-grid" style={{ marginTop: 18 }}><Card><h2>Variable objetivo</h2><div className="code-label">clasificacion_reproductiva</div><p>Cuatro clases desbalanceadas: Excelente es apenas el 3,8% del rodeo, por eso el modelo se mide con F1 macro y no con accuracy.</p><div className="metric-placeholder"><span>F1 macro en prueba</span><strong>0.871</strong><small>Baseline de clase mayoritaria: 0.167</small></div></Card><Card><h2>Lo que más pesa</h2><ul className="check-list"><li><CheckCircle2 size={16} /> intervalo entre partos</li><li><CheckCircle2 size={16} /> producción de leche</li><li><CheckCircle2 size={16} /> meses desde el último parto</li><li><CheckCircle2 size={16} /> pérdida de cría</li></ul><p style={{ marginTop: 14, fontSize: 11.5 }}>Medido por permutación sobre datos de prueba. El resto de variables —peso, edad, color— apenas cambian el resultado.</p></Card></div></> }
function SettingsView() { return <><PageTitle eyebrow="Preferencias y alcance" title="Configuración" description="Información sobre esta instancia y los límites actuales del MVP." /><div className="settings-list"><Card><div className="setting-row"><div className="setting-icon"><Database size={18} /></div><div><h2>Fuente de datos</h2><p>Datos sintéticos locales cargados desde una capa de servicio separada.</p></div><span className="source-tag">Demo</span></div></Card><Card><div className="setting-row"><div className="setting-icon"><ShieldCheck size={18} /></div><div><h2>Uso responsable</h2><p>CampoClaro es una herramienta de apoyo. No reemplaza la evaluación veterinaria ni las decisiones del equipo.</p></div></div></Card><Card><div className="setting-row"><div className="setting-icon"><Activity size={18} /></div><div><h2>Próximos pasos</h2><p>Conectar SQLite + FastAPI, autenticar usuarios y entrenar un modelo validado con datos históricos.</p></div><ChevronRight size={18} /></div></Card></div></> }

export default function Page() {
  const [started, setStarted] = useState(false); const [view, setView] = useState<View>('inicio'); const [mobile, setMobile] = useState(false)
  const [cows, setCows] = useState<Cow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const [charts, setCharts] = useState<ChartSpec[]>([])
  // Las gráficas nuevas se apilan arriba y se conservan hasta que el usuario limpie.
  const addCharts = useCallback((nuevas: ChartSpec[]) => { setCharts(prev => [...nuevas, ...prev].slice(0, 8)); setView('inicio') }, [])

  const reload = useCallback(() => { setLoading(true); api.listCows().then(data => { setCows(data); setError(null) }).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { reload() }, [reload])

  const addCow = useCallback(async () => {
    const earTag = window.prompt('Caravana de la nueva vaca', `BOV-${String(cows.length + 1).padStart(3, '0')}`)
    if (!earTag) return
    try { await api.createCow({ earTag, breed: 'Holstein', status: 'Activa', birthDate: new Date().toISOString().slice(0, 10), parity: 1, intervalMonths: 0, milkLiters: 0, bodyCondition: 3, healthEvents: 0, notes: '' }); reload() }
    catch (err) { alert(`No se pudo registrar: ${(err as Error).message}`) }
  }, [cows.length, reload])

  if (!started) return <Landing enter={() => setStarted(true)} />; return <div className="app-shell"><Sidebar view={view} setView={setView} mobile={mobile} close={() => setMobile(false)} /><main className="app-main"><header className="app-header"><button className="menu-toggle" onClick={() => setMobile(true)} aria-label="Abrir menú"><Menu size={20} /></button><div className="breadcrumb"><span>Establecimiento Norte</span><ChevronRight size={14} /><strong>{nav.find(n => n.id === view)?.label}</strong></div><div className="header-actions"><span className="status-online"><i /> Sistema operativo</span><button className="icon-btn"><Bell size={18} /></button><div className="avatar">OP</div></div></header><div className="content">{loading ? <p className="empty">Cargando datos del rodeo...</p> : error ? <p className="empty">No se pudo conectar con el backend: {error}</p> : <Dashboard cows={cows} addCow={addCow} reload={reload} view={view} setView={setView} charts={charts} clearCharts={() => setCharts([])} />}</div></main><CowBot apiBase={api.baseUrl} onCharts={addCharts} /></div> }
